### ISSUE TITLE
'kced' in script (go lang deck). Should we change it? 

### ISSUE THREAD

**Issue by granthbr** [KongHQ-CX/kong-api-ops-samples#1]
I understand that 'kced' is currently in the deploy script. Doesn't the latest version of 'deck' implement the functionality that 'kced' is used for in the deploy script? Or is it better to use 'go-apiops'?

**Comment by ttyS0e** [comment]
No it's not, sorry @granthbr , I fixed that one script now.

**Comment by ttyS0e** [comment]
Fixed in 949c9ce459d1dc33bb88ffdc369d3a689342e52f
